version: 2.1
jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t ${DOCKER_USERNAME}/jarvis-text-summarizer:latest .
      - run:
          name: Log in to Docker Hub
          command: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
      - run:
          name: Push Docker image
          command: docker push ${DOCKER_USERNAME}/jarvis-text-summarizer:latest
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
